apiVersion: v1
kind: Service
metadata:
  name: springboot-mybatis-mysql
  namespace: default
  labels:
    app: springboot-mybatis-mysql
spec:
  ports:
    - port: 8080
      targetPort: 8080
  selector:
    app: springboot-mybatis-mysql
  type: LoadBalancer